export const surah = [
  {
    id: 1,
    title: 'Al-Fatiha',
    artist: 'The Opening',
    total_verses: 7,
    url: 'http://download.quranurdu.com/Al%20Quran%20with%20Urdu%20Translation%20by%20Abdul%20Rahman%20Al-Sudais/001%20Al%20Fatihah/1%20Al%20Fatiha-quranurdu.com.mp3',
  },
  {
    id: 2,
    title: 'Al-Baqarah',
    artist: 'The Cow',
    total_verses: 286,
    url: 'http://download.quranurdu.com/Al%20Quran%20with%20Urdu%20Translation%20by%20Abdul%20Rahman%20Al-Sudais/002%20Al%20Baqarah/002-Al%20Baqarah-Ruku-01-quranurdu.com.mp3',
  },
  {
    id: 3,
    title: 'Aali Imran',
    artist: 'The Family of Imran',
    total_verses: 200,
    url: 'http://download.quranurdu.com/Al%20Quran%20with%20Urdu%20Translation%20by%20Abdul%20Rahman%20Al-Sudais/003%20Ale%20Imran/003-Ale%20Imran-Ruku-01-quranurdu.com.mp3',
  },
]
//   {
//     id: 4,
//     title: 'An-Nisa',
//     artist: 'The Women',
//     total_verses: 176,
//   },
//   {
//     id: 5,
//     title: "Al-Ma'idah",
//     artist: 'The Table Spread',
//     total_verses: 120,
//   },
//   {
//     id: 6,
//     title: "Al-An'am",
//     artist: 'The Cattle',
//     total_verses: 165,
//   },
//   {
//     id: 7,
//     title: "Al-A'raf",
//     artist: 'The Heights',
//     total_verses: 206,
//   },
//   {
//     id: 8,
//     title: 'Al-Anfal',
//     artist: 'The Spoils of War',
//     total_verses: 75,
//   },
//   {
//     id: 9,
//     title: 'At-Tawbah',
//     artist: 'The Repentance',
//     total_verses: 129,
//   },
//   {
//     id: 10,
//     title: 'Yunus',
//     artist: 'Jonah',
//     total_verses: 109,
//   },
//   {
//     id: 11,
//     title: 'Hud',
//     artist: 'Hud',
//     total_verses: 123,
//   },
//   {
//     id: 12,
//     title: 'Yusuf',
//     artist: 'Joseph',
//     total_verses: 111,
//   },
//   {
//     id: 13,
//     title: "Ar-Ra'd",
//     artist: 'The Thunder',
//     total_verses: 43,
//   },
//   {
//     id: 14,
//     title: 'Ibrahim',
//     artist: 'Abraham',
//     total_verses: 52,
//   },
//   {
//     id: 15,
//     title: 'Al-Hijr',
//     artist: 'The Rocky Tract',
//     total_verses: 99,
//   },
//   {
//     id: 16,
//     title: 'An-Nahl',
//     artist: 'The Bee',
//     total_verses: 128,
//   },
//   {
//     id: 17,
//     title: 'Al-Isra',
//     artist: 'The Night Journey',
//     total_verses: 111,
//   },
//   {
//     id: 18,
//     title: 'Al-Kahf',
//     artist: 'The Cave',
//     total_verses: 110,
//   },
//   {
//     id: 19,
//     title: 'Maryam',
//     artist: 'Mary',
//     total_verses: 98,
//   },
//   {
//     id: 20,
//     title: 'Ta-Ha',
//     artist: 'Ta-Ha',
//     total_verses: 135,
//   },
//   {
//     id: 21,
//     title: 'Al-Anbiya',
//     artist: 'The Prophets',
//     total_verses: 112,
//   },
//   {
//     id: 22,
//     title: 'Al-Hajj',
//     artist: 'The Pilgrimage',
//     total_verses: 78,
//   },
//   {
//     id: 23,
//     title: "Al-Mu'minun",
//     artist: 'The Believers',
//     total_verses: 118,
//   },
//   {
//     id: 24,
//     title: 'An-Nur',
//     artist: 'The Light',
//     total_verses: 64,
//   },
//   {
//     id: 25,
//     title: 'Al-Furqan',
//     artist: 'The Criterion',
//     total_verses: 77,
//   },
//   {
//     id: 26,
//     title: "Ash-Shu'ara",
//     artist: 'The Poets',
//     total_verses: 227,
//   },
//   {
//     id: 27,
//     title: 'An-Naml',
//     artist: 'The Ant',
//     total_verses: 93,
//   },
//   {
//     id: 28,
//     title: 'Al-Qasas',
//     artist: 'The Stories',
//     total_verses: 88,
//   },
//   {
//     id: 29,
//     title: 'Al-Ankabut',
//     artist: 'The Spider',
//     total_verses: 69,
//   },
//   {
//     id: 30,
//     title: 'Ar-Rum',
//     artist: 'The Romans',
//     total_verses: 60,
//   },
//   {
//     id: 31,
//     title: 'Luqman',
//     artist: 'Luqman',
//     total_verses: 34,
//   },
//   {
//     id: 32,
//     title: 'As-Sajda',
//     artist: 'The Prostration',
//     total_verses: 30,
//   },
//   {
//     id: 33,
//     title: 'Al-Ahzab',
//     artist: 'The Confederates',
//     total_verses: 73,
//   },
//   {
//     id: 34,
//     title: 'Saba',
//     artist: 'Sheba',
//     total_verses: 54,
//   },
//   {
//     id: 35,
//     title: 'Fatir',
//     artist: 'The Originator',
//     total_verses: 45,
//   },
//   {
//     id: 36,
//     title: 'Ya-Sin',
//     artist: 'Ya-Sin',
//     total_verses: 83,
//   },
//   {
//     id: 37,
//     title: 'As-Saffat',
//     artist: 'Those who set the Ranks',
//     total_verses: 182,
//   },
//   {
//     id: 38,
//     title: 'Sad',
//     artist: 'The Letter Sad',
//     total_verses: 88,
//   },
//   {
//     id: 39,
//     title: 'Az-Zumar',
//     artist: 'The Groups',
//     total_verses: 75,
//   },
//   {
//     id: 40,
//     title: 'Ghafir',
//     artist: 'The Forgiver',
//     total_verses: 85,
//   },
//   {
//     id: 41,
//     title: 'Fussilat',
//     artist: 'Explained in Detail',
//     total_verses: 54,
//   },
//   {
//     id: 42,
//     title: 'Ash-Shura',
//     artist: 'The Consultation',
//     total_verses: 53,
//   },
//   {
//     id: 43,
//     title: 'Az-Zukhruf',
//     artist: 'The Gold Adornments',
//     total_verses: 89,
//   },
//   {
//     id: 44,
//     title: 'Ad-Dukhan',
//     artist: 'The Smoke',
//     total_verses: 59,
//   },
//   {
//     id: 45,
//     title: 'Al-Jathiya',
//     artist: 'The Crouching',
//     total_verses: 37,
//   },
//   {
//     id: 46,
//     title: 'Al-Ahqaf',
//     artist: 'The Wind-Curved Sandhills',
//     total_verses: 35,
//   },
//   {
//     id: 47,
//     title: 'Muhammad',
//     artist: 'Muhammad',
//     total_verses: 38,
//   },
//   {
//     id: 48,
//     title: 'Al-Fath',
//     artist: 'The Victory',
//     total_verses: 29,
//   },
//   {
//     id: 49,
//     title: 'Al-Hujurat',
//     artist: 'The Rooms',
//     total_verses: 18,
//   },
//   {
//     id: 50,
//     title: 'Qaf',
//     artist: 'The Letter Qaf',
//     total_verses: 45,
//   },
//   {
//     id: 51,
//     title: 'Adh-Dhariyat',
//     artist: 'The Winnowing Winds',
//     total_verses: 60,
//   },
//   {
//     id: 52,

//     title: 'At-Tur',
//     artist: 'The Mount',
//     total_verses: 49,
//   },
//   {
//     id: 53,
//     title: 'An-Najm',
//     artist: 'The Star',
//     total_verses: 62,
//   },
//   {
//     id: 54,
//     title: 'Al-Qamar',
//     artist: 'The Moon',
//     total_verses: 55,
//   },
//   {
//     id: 55,
//     title: 'Ar-Rahman',
//     artist: 'The Beneficent',
//     total_verses: 78,
//   },
//   {
//     id: 56,
//     title: 'Al-Waqia',
//     artist: 'The Inevitable',
//     total_verses: 96,
//   },
//   {
//     id: 57,
//     title: 'Al-Hadid',
//     artist: 'The Iron',
//     total_verses: 29,
//   },
//   {
//     id: 58,
//     title: 'Al-Mujadila',
//     artist: 'The Pleading Woman',
//     total_verses: 22,
//   },
//   {
//     id: 59,
//     title: 'Al-Hashr',
//     artist: 'The Exile',
//     total_verses: 24,
//   },
//   {
//     id: 60,
//     title: 'Al-Mumtahina',
//     artist: 'She that is to be Examined',
//     total_verses: 13,
//   },
//   {
//     id: 61,
//     title: 'As-Saff',
//     artist: 'The Ranks',
//     total_verses: 14,
//   },
//   {
//     id: 62,
//     title: 'Al-Jumua',
//     artist: 'The Congregation',
//     total_verses: 11,
//   },
//   {
//     id: 63,
//     title: 'Al-Munafiqun',
//     artist: 'The Hypocrites',
//     total_verses: 11,
//   },
//   {
//     id: 64,
//     title: 'At-Taghabun',
//     artist: 'The Mutual Disillusion',
//     total_verses: 18,
//   },
//   {
//     id: 65,
//     title: 'At-Talaq',
//     artist: 'The Divorce',
//     total_verses: 12,
//   },
//   {
//     id: 66,
//     title: 'At-Tahrim',
//     artist: 'The Prohibition',
//     total_verses: 12,
//   },
//   {
//     id: 67,
//     title: 'Al-Mulk',
//     artist: 'The Sovereignty',
//     total_verses: 30,
//   },
//   {
//     id: 68,
//     title: 'Al-Qalam',
//     artist: 'The Pen',
//     total_verses: 52,
//   },
//   {
//     id: 69,
//     title: 'Al-Haqqah',
//     artist: 'The Reality',
//     total_verses: 52,
//   },
//   {
//     id: 70,
//     title: 'Al-Maarij',
//     artist: 'The Ascending Stairways',
//     total_verses: 44,
//   },
//   {
//     id: 71,
//     title: 'Nuh',
//     artist: 'Noah',
//     total_verses: 28,
//   },
//   {
//     id: 72,
//     title: 'Al-Jinn',
//     artist: 'The Jinn',
//     total_verses: 28,
//   },
//   {
//     id: 73,
//     title: 'Al-Muzzammil',
//     artist: 'The Enshrouded One',
//     total_verses: 20,
//   },
//   {
//     id: 74,
//     title: 'Al-Muddathir',
//     artist: 'The Cloaked One',
//     total_verses: 56,
//   },
//   {
//     id: 75,
//     title: 'Al-Qiyama',
//     artist: 'The Resurrection',
//     total_verses: 40,
//   },
//   {
//     id: 76,
//     title: 'Al-Insan',
//     artist: 'Man',
//     total_verses: 31,
//   },
//   {
//     id: 77,
//     title: 'Al-Mursalat',
//     artist: 'The Emissaries',
//     total_verses: 50,
//   },
//   {
//     id: 78,
//     title: 'An-Naba',
//     artist: 'The Tidings',
//     total_verses: 40,
//   },
//   {
//     id: 79,
//     title: 'An-Naziat',
//     artist: 'Those who drag forth',
//     total_verses: 46,
//   },
//   {
//     id: 80,
//     title: 'Abasa',
//     artist: 'He frowned',
//     total_verses: 42,
//   },
//   {
//     id: 81,
//     title: 'At-Takwir',
//     artist: 'The Overthrowing',
//     total_verses: 29,
//   },
//   {
//     id: 82,
//     title: 'Al-Infitar',
//     artist: 'The Cleaving',
//     total_verses: 19,
//   },
//   {
//     id: 83,
//     title: 'Al-Mutaffifin',
//     artist: 'Defrauding',
//     total_verses: 36,
//   },
//   {
//     id: 84,
//     title: 'Al-Inshiqaq',
//     artist: 'The Splitting Open',
//     total_verses: 25,
//   },
//   {
//     id: 85,
//     title: 'Al-Buruj',
//     artist: 'The Mansions of the Stars',
//     total_verses: 22,
//   },
//   {
//     id: 86,
//     title: 'At-Tariq',
//     artist: 'The Morning Star',
//     total_verses: 17,
//   },
//   {
//     id: 87,
//     title: 'Al-Ala',
//     artist: 'The Most High',
//     total_verses: 19,
//   },
//   {
//     id: 88,
//     title: 'Al-Ghashiya',
//     artist: 'The Overwhelming',
//     total_verses: 26,
//   },
//   {
//     id: 89,
//     title: 'Al-Fajr',
//     artist: 'The Dawn',
//     total_verses: 30,
//   },
//   {
//     id: 90,
//     title: 'Al-Balad',
//     artist: 'The City',
//     total_verses: 20,
//   },
//   {
//     id: 91,
//     title: 'Ash-Shams',
//     artist: 'The Sun',
//     total_verses: 15,
//   },
//   {
//     id: 92,
//     title: 'Al-Lail',
//     artist: 'The Night',
//     total_verses: 21,
//   },
//   {
//     id: 93,
//     title: 'Ad-Duha',
//     artist: 'The Morning Hours',
//     total_verses: 11,
//   },
//   {
//     id: 94,
//     title: 'Ash-Sharh',
//     artist: 'The Relief',
//     total_verses: 8,
//   },
//   {
//     id: 95,
//     title: 'At-Tin',
//     artist: 'The Fig',
//     total_verses: 8,
//   },
//   {
//     id: 96,
//     title: 'Al-Alaq',
//     artist: 'The Clot',
//     total_verses: 19,
//   },
//   {
//     id: 97,
//     title: 'Al-Qadr',
//     artist: 'The Power',
//     total_verses: 5,
//   },
//   {
//     id: 98,
//     title: 'Al-Bayyina',
//     artist: 'The Clear Proof',
//     total_verses: 8,
//   },
//   {
//     id: 99,
//     title: 'Az-Zalzalah',
//     artist: 'The Earthquake',
//     total_verses: 8,
//   },
//   {
//     id: 100,
//     title: 'Al-Adiyat',
//     artist: 'The Courser',
//     total_verses: 11,
//   },
//   {
//     id: 101,
//     title: 'Al-Qaria',
//     artist: 'The Calamity',
//     total_verses: 11,
//   },
//   {
//     id: 102,
//     title: 'At-Takathur',
//     artist: 'Rivalry in worldly increase',
//     total_verses: 8,
//   },
//   {
//     id: 103,
//     title: 'Al-Asr',
//     artist: 'The Declining Day',
//     total_verses: 3,
//   },
//   {
//     id: 104,
//     title: 'Al-Humaza',
//     artist: 'The Traducer',
//     total_verses: 9,
//   },
//   {
//     id: 105,
//     title: 'Al-Fil',
//     artist: 'The Elephant',
//     total_verses: 5,
//   },
//   {
//     id: 106,
//     title: 'Quraish',
//     artist: 'Quraish',
//     total_verses: 4,
//   },
//   {
//     id: 107,
//     title: 'Al-Maun',
//     artist: 'The Small Kindnesses',
//     total_verses: 7,
//   },
//   {
//     id: 108,
//     title: 'Al-Kawthar',
//     artist: 'The Abundance',
//     total_verses: 3,
//   },
//   {
//     id: 109,
//     title: 'Al-Kafirun',
//     artist: 'The Disbelievers',
//     total_verses: 6,
//   },
//   {
//     id: 110,
//     title: 'An-Nasr',
//     artist: 'The Divine Support',
//     total_verses: 3,
//   },
//   {
//     id: 111,
//     title: 'Al-Masad',
//     artist: 'The Palm Fiber',
//     total_verses: 5,
//   },
//   {
//     id: 112,
//     title: 'Al-Ikhlas',
//     artist: 'The Sincerity',
//     total_verses: 4,
//   },
//   {
//     id: 113,
//     title: 'Al-Falaq',
//     artist: 'The Daybreak',
//     total_verses: 5,
//   },
//   {
//     id: 114,
//     title: 'An-Nas',
//     artist: 'Mankind',
//     total_verses: 6,
//   },
// ];
